- name: Register clients with IPA Server
  hosts: ipa_clients 
  become: yes
  remote_user: "{{ ansible_user }}"
  vars:
    - ansible_domain: 
    - ipa_server:
    - ipa_host:
    - ipa_port: 
    - ipa_admin_username:
    - ipa_admin_password:
  tasks:
    - name: Include IPA client Installation and Registration role 
      include_role:
        name: install-and-register-dns-client 
      when:
        - hostvars[inventory_hostname]['install_ipa_client'] is defined
        - hostvars[inventory_hostname]['install_ipa_client'] | bool == true


- name: Register clients with IPA Server
  hosts: ipa_hosts
  become: yes
  remote_user: "{{ ansible_user }}"
  vars:
    - ansible_domain: 
    - ipa_server:
    - ipa_host:
    - ipa_port: 
    - ipa_admin_username:
    - ipa_admin_password:
    - add_hosts_to_ipa: true
  vars_files:
    - hosts_info.yml
  tasks:
    - name: Include IPA clients registration tasks file
      include_role:
        name: install-and-register-dns-client
        tasks_from: register-host-with-dns-server.yml
      when:
        - add_hosts_to_ipa is defined
        - add_hosts_to_ipa | bool

